apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: health-service
  template:
    metadata:
      labels:
        app: health-service
    spec:
      containers:
        - name: health-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: health-service-config
            - secretRef:
                name: health-service-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
