apiVersion: v1
kind: Secret
metadata:
  name: health-service-secret
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
