apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: health-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
